java "-javaagent:/Applications/IntelliJ IDEA 2.app/Contents/lib/idea_rt.jar=53241:/Applications/IntelliJ IDEA 2.app/Contents/bin" -Dfile.encoding=UTF-8
 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/tools.jar:
 /Users/open/IdeaProjects/sitexa/sitexa-api/target/classes:
 /Users/open/IdeaProjects/libs/commons-codec-1.4.jar:
 /Users/open/IdeaProjects/libs/commons-httpclient-3.1.jar:
 /Users/open/IdeaProjects/libs/commons-logging-1.1.1.jar:
 /Users/open/IdeaProjects/libs/dsn.jar:
 /Users/open/IdeaProjects/libs/gimap.jar:
 /Users/open/IdeaProjects/libs/imap.jar:
 /Users/open/IdeaProjects/libs/mailapi.jar:
 /Users/open/IdeaProjects/libs/pop3.jar:
 /Users/open/IdeaProjects/libs/smtp.jar:
 /Users/open/.m2/repository/com/squareup/okhttp3/okhttp/3.6.0/okhttp-3.6.0.jar:
 /Users/open/.m2/repository/com/squareup/okio/okio/1.11.0/okio-1.11.0.jar:
 /Users/open/.m2/repository/org/jetbrains/exposed/exposed/0.7.6/exposed-0.7.6.jar:
 /Users/open/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar:
 /Users/open/.m2/repository/org/mariadb/jdbc/mariadb-java-client/1.5.9/mariadb-java-client-1.5.9.jar:
 /Users/open/.m2/repository/com/zaxxer/hikariCP/2.6.0/HikariCP-2.6.0.jar:
 /Users/open/.m2/repository/org/ehcache/ehcache/3.0.0.m4/ehcache-3.0.0.m4.jar:
 /Users/open/.m2/repository/org/terracotta/offheap-store/2.1.2/offheap-store-2.1.2.jar:
 /Users/open/.m2/repository/joda-time/joda-time/2.9.2/joda-time-2.9.2.jar:
 /Users/open/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar:
 /Users/open/.m2/repository/com/squareup/moshi/moshi/1.4.0/moshi-1.4.0.jar:
 /Users/open/.m2/repository/com/github/salomonbrys/kotson/kotson/2.5.0/kotson-2.5.0.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-locations/0.3.2/ktor-locations-0.3.2.jar:
 /Users/open/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jre8/1.1.1/kotlin-stdlib-jre8-1.1.1.jar:
 /Users/open/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.1.1/kotlin-stdlib-jre7-1.1.1.jar:
 /Users/open/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.14/kotlinx-coroutines-core-0.14.jar:
 /Users/open/.m2/repository/org/jetbrains/kotlin/kotlin-runtime/1.1.2/kotlin-runtime-1.1.2.jar:
 /Users/open/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:
 /Users/open/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.1.2/kotlin-reflect-1.1.2.jar:
 /Users/open/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.1.2/kotlin-stdlib-1.1.2.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-core/0.3.2/ktor-core-0.3.2.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-jetty/0.3.2/ktor-jetty-0.3.2.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-hosts-common/0.3.2/ktor-hosts-common-0.3.2.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-servlet/0.3.2/ktor-servlet-0.3.2.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-server/9.4.1.v20170120/jetty-server-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-http/9.4.1.v20170120/jetty-http-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-io/9.4.1.v20170120/jetty-io-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-servlets/9.4.1.v20170120/jetty-servlets-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-continuation/9.4.1.v20170120/jetty-continuation-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-util/9.4.1.v20170120/jetty-util-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/jetty-alpn-server/9.4.1.v20170120/jetty-alpn-server-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/http2/http2-server/9.4.1.v20170120/http2-server-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/http2/http2-common/9.4.1.v20170120/http2-common-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/http2/http2-hpack/9.4.1.v20170120/http2-hpack-9.4.1.v20170120.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-netty/0.3.2/ktor-netty-0.3.2.jar:
 /Users/open/.m2/repository/io/netty/netty-codec-http2/4.1.9.Final/netty-codec-http2-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-codec-http/4.1.9.Final/netty-codec-http-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-codec/4.1.9.Final/netty-codec-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-handler/4.1.9.Final/netty-handler-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-buffer/4.1.9.Final/netty-buffer-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-common/4.1.9.Final/netty-common-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-transport/4.1.9.Final/netty-transport-4.1.9.Final.jar:
 /Users/open/.m2/repository/io/netty/netty-resolver/4.1.9.Final/netty-resolver-4.1.9.Final.jar:
 /Users/open/.m2/repository/org/eclipse/jetty/alpn/alpn-api/1.1.3.v20160715/alpn-api-1.1.3.v20160715.jar:
 /Users/open/.m2/repository/org/jetbrains/ktor/ktor-auth/0.3.2/ktor-auth-0.3.2.jar:
 /Users/open/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:
 /Users/open/.m2/repository/junit/junit/4.10/junit-4.10.jar:
 /Users/open/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:
 /Users/open/.m2/repository/org/slf4j/jul-to-slf4j/1.7.12/jul-to-slf4j-1.7.12.jar:
 /Users/open/.m2/repository/ch/qos/logback/logback-classic/1.2.1/logback-classic-1.2.1.jar:
 /Users/open/.m2/repository/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar:
 /Users/open/.m2/repository/com/typesafe/config/1.2.1/config-1.2.1.jar org.jetbrains.ktor.netty.DevelopmentHost
